Yang bam2 add landing page
iobio/bam.iobio pull request #2
Opened 2024-09-16 18:20 UTC by YangQi007

2024-09-16 20:06 UTC, anderspitman requested changes

2024-09-16 20:06 UTC, anderspitman commented on home_page.js
> +            this.navigateToMainContent(url1, url2);
As a quick hack, this worked for me:

```javascript
setTimeout(() => {
  this.navigateToMainContent(url1, url2);
}, 1000);
```

2024-09-16 20:06 UTC, anderspitman commented on localFile_input_modal.js
> +        input.accept = index === '0' ? '.bam,.cram' : '.bai,.crai';
The way you're doing this is confusing to me. You're using the indexes to indicate the type, then reverse engineering it here. I think it would be cleaner to just keep the files in separate objects, rather than an array. Then you always know which one is which, and you'll be less likely to end up with bugs where they get mixed up.

2024-09-17 00:36 UTC, YangQi007 commented on localFile_input_modal.js
> +        input.accept = index === '0' ? '.bam,.cram' : '.bai,.crai';
The index here is used to distinguish the two selection buttons and the two inputs. The first button is used to select the `.bam/.cram`; the second is used to select the `.bai/.crai`. The first input is only allowed to accept the `.bam/.cram`; the second is only allowed to accept the `.bai/.crai'. This solution considered your suggestion a while ago that we separate and validate the inputs types instead of allowing the user to input two files together in a different order(the old solution in bam1), which made the code more complex for the file validation. 

`   this.deleteIcons.forEach((icon, index) => {
            icon.addEventListener('click', () => this.clearInput(index));
        });
        this.selectFileButtons.forEach((button) => {
            button.addEventListener('click', (event) => this.selectFile(event.target.dataset.index));
        });`

2024-09-17 00:48 UTC, anderspitman commented on localFile_input_modal.js
> +        input.accept = index === '0' ? '.bam,.cram' : '.bai,.crai';
Yes, I like the UX of the design, but I think the implementation is confusing. My concern is that you have defined 0 to mean bam and 1 to mean bai. 0 and 1 have nothing to do with bam and bai. So when another developer sees code that equates them, they have to keep looking around before they understand why. That's what happened with me earlier today.

One simple improvement would be to use actual names instead of indexes, so instead of `data-index="0"` you would have something like `data-key="bam-cram"` or `data-key="alignment-file"`. Then you would store them in a map instead of an array.

But I think it would be better to just separate them completely. I think the main difference is you would have two calls in most places, instead of a forEach loop. If we were expecting the number of inputs to grow, it might make more sense for it to be a loop, but I don't think that is the case.

2024-09-17 17:03 UTC, anderspitman approved these changes
Looks great. Using a callback is pretty old school. I would probably return a promise from `selectFile` that resolves with a file when it's ready. But the code is small and it's clear what it does, so not critical.

2024-09-17 17:03 UTC, merged