Added static files from s3
iobio/bam.iobio pull request #23
Opened 2024-11-20 20:36 UTC by YangQi007

2024-11-20 23:19 UTC, anderspitman requested changes

2024-11-20 23:19 UTC, anderspitman commented on home_page.js
> +            <div id="marthlabtext">Marthlab</div>
"Marthlab" is showing up as blue for me. Can you make it match the gray text color from bam1?

2024-11-20 23:44 UTC, anderspitman requested changes
Looks good. I think you just need to merge the latest main to fix the iobio-charts conflicts.

2024-11-26 00:46 UTC, YangQi007 commented
> Looks good. I think you just need to merge the latest main to fix the iobio-charts conflicts.

Just merged main to this branch.

2024-11-26 00:53 UTC, merged